name: Yaml Lint
on: [push] 
concurrency:
  group: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref_type != 'tag' }}

jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: index.yaml
          config_data: "{extends: default, rules: {new-line-at-end-of-file: disable, document-start: disable, line-length: {max: 200}, trailing-spaces: disable}}"
